[package]
name = "hamming"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "greetings"
crate-type = ["staticlib", "cdylib"]

[dependencies]
rand = "0.8.4"